CREATE TABLE EMPLOYEE (
    EMPLOYEE_ID NUMBER(6),
    LAST_NAME VARCHAR2(25),
    JOB_ID VARCHAR2(10),
    SALARY NUMBER(8,2),
    COMM_PCT NUMBER(4,2),
    MGR_ID NUMBER(6),
    DEPARTMENT_ID NUMBER(4)
);